CameraModel.create(brand: "SONY", name: "DSLR-a100",  mount: "A-mount")
CameraModel.create(brand: "SONY", name: "DSLR-a200",  mount: "A-mount")
CameraModel.create(brand: "SONY", name: "DSLR-a230",  mount: "A-mount")
CameraModel.create(brand: "SONY", name: "DSLR-a290",  mount: "A-mount")
CameraModel.create(brand: "SONY", name: "DSLR-a300",  mount: "A-mount")
CameraModel.create(brand: "SONY", name: "DSLR-a330",  mount: "A-mount")
CameraModel.create(brand: "SONY", name: "DSLR-a350",  mount: "A-mount")
CameraModel.create(brand: "SONY", name: "DSLR-a380",  mount: "A-mount")
CameraModel.create(brand: "SONY", name: "DSLR-a390",  mount: "A-mount")
CameraModel.create(brand: "SONY", name: "DSLR-a450",  mount: "A-mount")
CameraModel.create(brand: "SONY", name: "DSLR-a500",  mount: "A-mount")
CameraModel.create(brand: "SONY", name: "DSLR-a550",  mount: "A-mount")
CameraModel.create(brand: "SONY", name: "DSLR-a560",  mount: "A-mount")
CameraModel.create(brand: "SONY", name: "DSLR-a580",  mount: "A-mount")
CameraModel.create(brand: "SONY", name: "DSLR-a700",  mount: "A-mount")
CameraModel.create(brand: "SONY", name: "DSLR-a850",  mount: "A-mount", ff: true)
CameraModel.create(brand: "SONY", name: "DSLR-a900",  mount: "A-mount", ff: true)
CameraModel.create(brand: "SONY", name: "SLT-a33",    mount: "A-mount")
CameraModel.create(brand: "SONY", name: "SLT-a35",    mount: "A-mount")
CameraModel.create(brand: "SONY", name: "SLT-a37",    mount: "A-mount")
CameraModel.create(brand: "SONY", name: "SLT-a55",    mount: "A-mount")
CameraModel.create(brand: "SONY", name: "SLT-a57",    mount: "A-mount")
CameraModel.create(brand: "SONY", name: "SLT-a58",    mount: "A-mount")
CameraModel.create(brand: "SONY", name: "SLT-a65",    mount: "A-mount")
CameraModel.create(brand: "SONY", name: "SLT-a77",    mount: "A-mount")
CameraModel.create(brand: "SONY", name: "SLT-a77 II", mount: "A-mount")
CameraModel.create(brand: "SONY", name: "SLT-a99",    mount: "A-mount", ff: true)
CameraModel.create(brand: "SONY", name: "NEX-3",      mount: "E-mount")
CameraModel.create(brand: "SONY", name: "NEX-C3",     mount: "E-mount")
CameraModel.create(brand: "SONY", name: "NEX-F3",     mount: "E-mount")
CameraModel.create(brand: "SONY", name: "NEX-3N",     mount: "E-mount")
CameraModel.create(brand: "SONY", name: "NEX-5",      mount: "E-mount")
CameraModel.create(brand: "SONY", name: "NEX-5N",     mount: "E-mount")
CameraModel.create(brand: "SONY", name: "NEX-5R",     mount: "E-mount")
CameraModel.create(brand: "SONY", name: "NEX-5T",     mount: "E-mount")
CameraModel.create(brand: "SONY", name: "NEX-6",      mount: "E-mount")
CameraModel.create(brand: "SONY", name: "NEX-7",      mount: "E-mount")
CameraModel.create(brand: "SONY", name: "a3000",      mount: "E-mount")
CameraModel.create(brand: "SONY", name: "a3500",      mount: "E-mount")
CameraModel.create(brand: "SONY", name: "a5000",      mount: "E-mount")
CameraModel.create(brand: "SONY", name: "a5100",      mount: "E-mount")
CameraModel.create(brand: "SONY", name: "a6000",      mount: "E-mount")
CameraModel.create(brand: "SONY", name: "7",          mount: "E-mount", ff: true)
CameraModel.create(brand: "SONY", name: "7R",         mount: "E-mount", ff: true)
CameraModel.create(brand: "SONY", name: "7S",         mount: "E-mount", ff: true)
CameraModel.create(brand: "SONY", name: "7 II",       mount: "E-mount", ff: true)
