# frozen_string_literal: true

CameraModel.create(brand: 'SONY', name: 'DSLR-a100',  mount: 'A-mount')
CameraModel.create(brand: 'SONY', name: 'DSLR-a200',  mount: 'A-mount')
CameraModel.create(brand: 'SONY', name: 'DSLR-a230',  mount: 'A-mount')
CameraModel.create(brand: 'SONY', name: 'DSLR-a290',  mount: 'A-mount')
CameraModel.create(brand: 'SONY', name: 'DSLR-a300',  mount: 'A-mount')
CameraModel.create(brand: 'SONY', name: 'DSLR-a330',  mount: 'A-mount')
CameraModel.create(brand: 'SONY', name: 'DSLR-a350',  mount: 'A-mount')
CameraModel.create(brand: 'SONY', name: 'DSLR-a380',  mount: 'A-mount')
CameraModel.create(brand: 'SONY', name: 'DSLR-a390',  mount: 'A-mount')
CameraModel.create(brand: 'SONY', name: 'DSLR-a450',  mount: 'A-mount')
CameraModel.create(brand: 'SONY', name: 'DSLR-a500',  mount: 'A-mount')
CameraModel.create(brand: 'SONY', name: 'DSLR-a550',  mount: 'A-mount')
CameraModel.create(brand: 'SONY', name: 'DSLR-a560',  mount: 'A-mount')
CameraModel.create(brand: 'SONY', name: 'DSLR-a580',  mount: 'A-mount')
CameraModel.create(brand: 'SONY', name: 'DSLR-a700',  mount: 'A-mount')
CameraModel.create(brand: 'SONY', name: 'DSLR-a850',  mount: 'A-mount', ff: true)
CameraModel.create(brand: 'SONY', name: 'DSLR-a900',  mount: 'A-mount', ff: true)
CameraModel.create(brand: 'SONY', name: 'SLT-a33',    mount: 'A-mount')
CameraModel.create(brand: 'SONY', name: 'SLT-a35',    mount: 'A-mount')
CameraModel.create(brand: 'SONY', name: 'SLT-a37',    mount: 'A-mount')
CameraModel.create(brand: 'SONY', name: 'SLT-a55',    mount: 'A-mount')
CameraModel.create(brand: 'SONY', name: 'SLT-a57',    mount: 'A-mount')
CameraModel.create(brand: 'SONY', name: 'SLT-a58',    mount: 'A-mount')
CameraModel.create(brand: 'SONY', name: 'SLT-a65',    mount: 'A-mount')
CameraModel.create(brand: 'SONY', name: 'SLT-a77',    mount: 'A-mount')
CameraModel.create(brand: 'SONY', name: 'SLT-a77 II', mount: 'A-mount')
CameraModel.create(brand: 'SONY', name: 'SLT-a99',    mount: 'A-mount', ff: true)
CameraModel.create(brand: 'SONY', name: 'NEX-3',      mount: 'E-mount')
CameraModel.create(brand: 'SONY', name: 'NEX-C3',     mount: 'E-mount')
CameraModel.create(brand: 'SONY', name: 'NEX-F3',     mount: 'E-mount')
CameraModel.create(brand: 'SONY', name: 'NEX-3N',     mount: 'E-mount')
CameraModel.create(brand: 'SONY', name: 'NEX-5',      mount: 'E-mount')
CameraModel.create(brand: 'SONY', name: 'NEX-5N',     mount: 'E-mount')
CameraModel.create(brand: 'SONY', name: 'NEX-5R',     mount: 'E-mount')
CameraModel.create(brand: 'SONY', name: 'NEX-5T',     mount: 'E-mount')
CameraModel.create(brand: 'SONY', name: 'NEX-6',      mount: 'E-mount')
CameraModel.create(brand: 'SONY', name: 'NEX-7',      mount: 'E-mount')
CameraModel.create(brand: 'SONY', name: 'a3000',      mount: 'E-mount')
CameraModel.create(brand: 'SONY', name: 'a3500',      mount: 'E-mount')
CameraModel.create(brand: 'SONY', name: 'a5000',      mount: 'E-mount')
CameraModel.create(brand: 'SONY', name: 'a5100',      mount: 'E-mount')
CameraModel.create(brand: 'SONY', name: 'a6000',      mount: 'E-mount')
CameraModel.create(brand: 'SONY', name: '7',          mount: 'E-mount', ff: true)
CameraModel.create(brand: 'SONY', name: '7R',         mount: 'E-mount', ff: true)
CameraModel.create(brand: 'SONY', name: '7S',         mount: 'E-mount', ff: true)
CameraModel.create(brand: 'SONY', name: '7 II',       mount: 'E-mount', ff: true)

hash = { 'a9' => { brand: 'SONY', full_name: 'Sony a9 (ILCE-9)', dyxum_link: 'http://www.dyxum.com/gear/camera/A9Sony_Alpha_A9.asp', dyxum_img_link: '/images/Cameras/57/57_1th.jpg', release_year: '2017', status: 'Announced', mount: 'E-mount', viewfinder: 'electronic', format: 'full frame (1x)', effective_pixels: '24MP', max_resolution: '6000x4000' },
         'a6500' => { brand: 'SONY', full_name: 'Sony a6500 (ILCE-6500)', dyxum_link: 'http://www.dyxum.com/gear/camera/A6500/Sony_Alpha_a6500.asp', dyxum_img_link: '/images/Cameras/56/56_1th.jpg', release_year: '2016', status: 'Current', mount: 'E-mount', viewfinder: 'electronic', format: 'APS-C (1.5x)', effective_pixels: '24.3MP', max_resolution: '6000x4000' },
         'a99II' => { brand: 'SONY', full_name: 'Sony a99II (ILCA-99M2)', dyxum_link: 'http://www.dyxum.com/gear/camera/a99II/Sony_Alpha_99II.asp', dyxum_img_link: '/images/Cameras/55/55_1th.jpg', release_year: '2016', status: 'Current', mount: 'A-mount', viewfinder: 'electronic', format: 'full frame (1x)', effective_pixels: '42.2MP', max_resolution: '7952x5304' },
         'a6300' => { brand: 'SONY', full_name: 'Sony a6300 (ILCE-6300)', dyxum_link: 'http://www.dyxum.com/gear/camera/A6300/Sony_Alpha_a6300.asp', dyxum_img_link: '/images/Cameras/54/54_1th.jpg', release_year: '2016', status: 'Current', mount: 'E-mount', viewfinder: 'electronic', format: 'APS-C (1.5x)', effective_pixels: '24.3MP', max_resolution: '6000x4000' },
         'SLT-a68' => { brand: 'SONY', full_name: 'Sony a68 (ILCA-68)', dyxum_link: 'http://www.dyxum.com/gear/camera/a68/Sony_Alpha_a68.asp', dyxum_img_link: '/images/Cameras/53/53_1th.jpg', release_year: '2016', status: 'Current', mount: 'A-mount', viewfinder: 'electronic', format: 'APS-C (1.5x)', effective_pixels: '24.3MP', max_resolution: '6000x4000' },
         'a7SII' => { brand: 'SONY', full_name: 'Sony a7SII (ILCE-7SM2)', dyxum_link: 'http://www.dyxum.com/gear/camera/A7SII/Sony_Alpha_A7SII.asp', dyxum_img_link: '/images/Cameras/52/52_1th.jpg', release_year: '2015', status: 'Current', mount: 'E-mount', viewfinder: 'electronic', format: 'full frame (1x)', effective_pixels: '12.2MP', max_resolution: '4240x2832' },
         'a7RII' => { brand: 'SONY', full_name: 'Sony a7RII (ILCE-7RM2)', dyxum_link: 'http://www.dyxum.com/gear/camera/A7RII/Sony_Alpha_A7RII.asp', dyxum_img_link: '/images/Cameras/51/51_1th.jpg', release_year: '2015', status: 'Current', mount: 'E-mount', viewfinder: 'electronic', format: 'full frame (1x)', effective_pixels: '42.4MP', max_resolution: '7974x5316' },
         '7 II' => { brand: 'SONY', full_name: 'Sony a7II (ILCE-7M2)', dyxum_link: 'http://www.dyxum.com/gear/camera/A7II/Sony_Alpha_A7II.asp', dyxum_img_link: '/images/Cameras/50/50_1th.jpg', release_year: '2014', status: 'Current', mount: 'E-mount', viewfinder: 'electronic', format: 'full frame (1x)', effective_pixels: '24MP', max_resolution: '6000x4000' },
         'a5100' => { brand: 'SONY', full_name: 'Sony a5100 (ILCE-5100)', dyxum_link: 'http://www.dyxum.com/gear/camera/A5100/Sony_Alpha_a5100.asp', dyxum_img_link: '/images/Cameras/49/49_1th.jpg', release_year: '2014', status: 'Current', mount: 'E-mount', viewfinder: 'none', format: 'APS-C (1.5x)', effective_pixels: '24.3MP', max_resolution: '6000x4000' },
         'SLT-a77 II' => { brand: 'SONY', full_name: 'Sony a77II (ILCA-77M2)', dyxum_link: 'http://www.dyxum.com/gear/camera/a77II/Sony_Alpha_77II.asp', dyxum_img_link: '/images/Cameras/48/48_1th.jpg', release_year: '2014', status: 'Current', mount: 'A-mount', viewfinder: 'electronic', format: 'APS-C (1.5x)', effective_pixels: '24.3MP', max_resolution: '6000x4000' },
         '7S' => { brand: 'SONY', full_name: 'Sony a7S (ILCE-7S)', dyxum_link: 'http://www.dyxum.com/gear/camera/A7S/Sony_Alpha_A7S.asp', dyxum_img_link: '/images/Cameras/47/47_1th.jpg', release_year: '2014', status: 'Current', mount: 'E-mount', viewfinder: 'electronic', format: 'full frame (1x)', effective_pixels: '12.2MP', max_resolution: '4240x2832' },
         'a6000' => { brand: 'SONY', full_name: 'Sony a6000 (ILCE-6000)', dyxum_link: 'http://www.dyxum.com/gear/camera/A6000/Sony_Alpha_a6000.asp', dyxum_img_link: '/images/Cameras/46/46_1th.jpg', release_year: '2014', status: 'Current', mount: 'E-mount', viewfinder: 'electronic', format: 'APS-C (1.5x)', effective_pixels: '24.3MP', max_resolution: '6000x4000' },
         'a5000' => { brand: 'SONY', full_name: 'Sony a5000 (ILCE-5000)', dyxum_link: 'http://www.dyxum.com/gear/camera/a5000/Sony_Alpha_a5000.asp', dyxum_img_link: '/images/Cameras/45/45_1th.jpg', release_year: '2014', status: 'Current', mount: 'E-mount', viewfinder: 'none', format: 'APS-C (1.5x)', effective_pixels: '20.1MP', max_resolution: '5456x3632' },
         '7' => { brand: 'SONY', full_name: 'Sony a7 (ILCE-7)', dyxum_link: 'http://www.dyxum.com/gear/camera/A7/Sony_Alpha_A7.asp', dyxum_img_link: '/images/Cameras/44/44_1th.jpg', release_year: '2013', status: 'Current', mount: 'E-mount', viewfinder: 'electronic', format: 'full frame (1x)', effective_pixels: '24MP', max_resolution: '6000x4000' },
         '7R' => { brand: 'SONY', full_name: 'Sony a7R (ILCE-7R)', dyxum_link: 'http://www.dyxum.com/gear/camera/A7R/Sony_Alpha_A7R.asp', dyxum_img_link: '/images/Cameras/32/32_1th.jpg', release_year: '2013', status: 'Current', mount: 'E-mount', viewfinder: 'electronic', format: 'full frame (1x)', effective_pixels: '36.2MP', max_resolution: '7360x4912' },
         'a3000' => { brand: 'SONY', full_name: 'Sony a3000 (ILCE-3000)', dyxum_link: 'http://www.dyxum.com/gear/camera/a3000/Sony_Alpha_a3000.asp ', dyxum_img_link: '/images/Cameras/363/6_1th.jpg', release_year: '2013', status: 'Current', mount: 'E-mount', viewfinder: 'electronic', format: 'APS-C (1.5x)', effective_pixels: '19.8MP', max_resolution: '5456x3632' },
         'NEX-5T' => { brand: 'SONY', full_name: 'Sony NEX-5T', dyxum_link: 'http://www.dyxum.com/gear/camera/NEX-5T/Sony_Alpha_NEX-5T.asp ', dyxum_img_link: '/images/Cameras/41/41_1th.jpg', release_year: '2013', status: 'Discontinued', mount: 'E-mount', viewfinder: 'optional', format: 'APS-C (1.5x)', effective_pixels: '16MP', max_resolution: '4912x3264' },
         'NEX-3N' => { brand: 'SONY', full_name: 'Sony NEX-3N', dyxum_link: 'http://www.dyxum.com/gear/camera/NEX-3N/Sony_Alpha_NEX-3N.asp ', dyxum_img_link: '/images/Cameras/37/37_1th.jpg', release_year: '2013', status: 'Discontinued', mount: 'E-mount', viewfinder: 'none', format: 'APS-C (1.5x)', effective_pixels: '16MP', max_resolution: '4912x3264' },
         'SLT-a58' => { brand: 'SONY', full_name: 'Sony a58', dyxum_link: 'http://www.dyxum.com/gear/camera/a58/Sony_Alpha_58.asp', dyxum_img_link: '/images/Cameras/31/31_1th.jpg', release_year: '2013', status: 'Current', mount: 'A-mount', viewfinder: 'electronic', format: 'APS-C (1.5x)', effective_pixels: '20.1MP', max_resolution: '5456x3632' },
         'NEX-6' => { brand: 'SONY', full_name: 'Sony NEX-6', dyxum_link: 'http://www.dyxum.com/gear/camera/NEX-6/Sony_Alpha_NEX-6.asp', dyxum_img_link: '/images/Cameras/42/42_1th.jpg', release_year: '2012', status: 'Discontinued', mount: 'E-mount', viewfinder: 'electronic', format: 'APS-C (1.5x)', effective_pixels: '16MP', max_resolution: '4912x3264' },
         'SLT-a99' => { brand: 'SONY', full_name: 'Sony a99', dyxum_link: 'http://www.dyxum.com/gear/camera/a99/Sony_Alpha_99.asp', dyxum_img_link: '/images/Cameras/29/29_1th.jpg', release_year: '2012', status: 'Current', mount: 'A-mount', viewfinder: 'electronic', format: 'full frame (1x)', effective_pixels: '24.3MP', max_resolution: '6000x4000' },
         'NEX-5R' => { brand: 'SONY', full_name: 'Sony NEX-5R', dyxum_link: 'http://www.dyxum.com/gear/camera/NEX-5R/Sony_Alpha_NEX-5R.asp ', dyxum_img_link: '/images/Cameras/40/40_1th.jpg', release_year: '2012', status: 'Discontinued', mount: 'E-mount', viewfinder: 'optional', format: 'APS-C (1.5x)', effective_pixels: '16MP', max_resolution: '4912x3264' },
         'NEX-F3' => { brand: 'SONY', full_name: 'Sony NEX-F3', dyxum_link: 'http://www.dyxum.com/gear/camera/NEX-F3/Sony_Alpha_NEX-F3.asp', dyxum_img_link: '/images/Cameras/35/35_1th.jpg', release_year: '2012', status: 'Discontinued', mount: 'E-mount', viewfinder: 'optional', format: 'APS-C (1.5x)', effective_pixels: '16MP', max_resolution: '4912x3264' },
         'SLT-a37' => { brand: 'SONY', full_name: 'Sony a37', dyxum_link: 'http://www.dyxum.com/gear/camera/a37/Sony_Alpha_37.asp', dyxum_img_link: '/images/Cameras/28/28_1th.jpg', release_year: '2012', status: 'Discontinued', mount: 'A-mount', viewfinder: 'electronic', format: 'APS-C (1.5x)', effective_pixels: '16.1MP', max_resolution: '4912x3264' },
         'SLT-a57' => { brand: 'SONY', full_name: 'Sony a57', dyxum_link: 'http://www.dyxum.com/gear/camera/a57/Sony_Alpha_57.asp', dyxum_img_link: '/images/Cameras/27/27_1th.jpg', release_year: '2012', status: 'Discontinued', mount: 'A-mount', viewfinder: 'electronic', format: 'APS-C (1.5x)', effective_pixels: '16.1MP', max_resolution: '4912x3264' },
         'NEX-7' => { brand: 'SONY', full_name: 'Sony NEX-7', dyxum_link: 'http://www.dyxum.com/gear/camera/NEX-7/Sony_Alpha_NEX-7.asp', dyxum_img_link: '/images/Cameras/43/43_1th.jpg', release_year: '2011', status: 'Discontinued', mount: 'E-mount', viewfinder: 'electronic', format: 'APS-C (1.5x)', effective_pixels: '24MP', max_resolution: '6000x4000' },
         'NEX-5N' => { brand: 'SONY', full_name: 'Sony NEX-5N', dyxum_link: 'http://www.dyxum.com/gear/camera/NEX-5N/Sony_Alpha_NEX-5N.asp ', dyxum_img_link: '/images/Cameras/39/39_1th.jpg', release_year: '2011', status: 'Discontinued', mount: 'E-mount', viewfinder: 'optional', format: 'APS-C (1.5x)', effective_pixels: '16MP', max_resolution: '4912x3264' },
         'SLT-a65' => { brand: 'SONY', full_name: 'Sony a65', dyxum_link: 'http://www.dyxum.com/gear/camera/a65/Sony_Alpha_65.asp', dyxum_img_link: '/images/Cameras/26/26_1th.jpg', release_year: '2011', status: 'Discontinued', mount: 'A-mount', viewfinder: 'electronic', format: 'APS-C (1.5x)', effective_pixels: '24.3MP', max_resolution: '6000x4000' },
         'SLT-a77' => { brand: 'SONY', full_name: 'Sony a77', dyxum_link: 'http://www.dyxum.com/gear/camera/a77/Sony_Alpha_77.asp', dyxum_img_link: '/images/Cameras/25/25_1th.jpg', release_year: '2011', status: 'Discontinued', mount: 'A-mount', viewfinder: 'electronic', format: 'APS-C (1.5x)', effective_pixels: '24.3MP', max_resolution: '6000x4000' },
         'NEX-C3' => { brand: 'SONY', full_name: 'Sony NEX-C3', dyxum_link: 'http://www.dyxum.com/gear/camera/NEX-C3/Sony_Alpha_NEX-C3.asp ', dyxum_img_link: '/images/Cameras/34/34_1th.jpg', release_year: '2011', status: 'Discontinued', mount: 'E-mount', viewfinder: 'none', format: 'APS-C (1.5x)', effective_pixels: '16MP', max_resolution: '4912x3264' },
         'SLT-a35' => { brand: 'SONY', full_name: 'Sony a35', dyxum_link: 'http://www.dyxum.com/gear/camera/a35/Sony_Alpha_35.asp', dyxum_img_link: '/images/Cameras/24/24_1th.jpg', release_year: '2011', status: 'Discontinued', mount: 'A-mount', viewfinder: 'electronic', format: 'APS-C (1.5x)', effective_pixels: '16.2MP', max_resolution: '4912x3264' },
         'DSLR-a350' => { brand: 'SONY', full_name: 'Sony a350', dyxum_link: 'http://www.dyxum.com/gear/camera/a350/Sony_Alpha_350.asp', dyxum_img_link: '/images/Cameras/8/8_1th.jpg', release_year: '2008', status: 'Discontinued', mount: 'A-mount', viewfinder: 'pentamirror', format: 'APS-C (1.5x)', effective_pixels: '14.2MP', max_resolution: '4592x3056' },
         'DSLR-a300' => { brand: 'SONY', full_name: 'Sony a300', dyxum_link: 'http://www.dyxum.com/gear/camera/a300/Sony_Alpha_300.asp', dyxum_img_link: '/images/Cameras/6/6_1th.jpg', release_year: '2008', status: 'Discontinued', mount: 'A-mount', viewfinder: 'pentamirror', format: 'APS-C (1.5x)', effective_pixels: '10.2MP', max_resolution: '3872x2592' },
         'SLT-a55' => { brand: 'SONY', full_name: 'Sony a55', dyxum_link: 'http://www.dyxum.com/gear/camera/a55/Sony_Alpha_55.asp', dyxum_img_link: '/images/Cameras/23/23_1th.jpg', release_year: '2010', status: 'Discontinued', mount: 'A-mount', viewfinder: 'electronic', format: 'APS-C (1.5x)', effective_pixels: '16.2MP', max_resolution: '4912x3264' },
         'SLT-a33' => { brand: 'SONY', full_name: 'Sony a33', dyxum_link: 'http://www.dyxum.com/gear/camera/a33/Sony_Alpha_33.asp', dyxum_img_link: '/images/Cameras/22/22_1th.jpg', release_year: '2010', status: 'Discontinued', mount: 'A-mount', viewfinder: 'electronic', format: 'APS-C (1.5x)', effective_pixels: '14.2MP', max_resolution: '4592x3056' },
         'DSLR-a580' => { brand: 'SONY', full_name: 'Sony a580', dyxum_link: 'http://www.dyxum.com/gear/camera/a580/Sony_Alpha_580.asp', dyxum_img_link: '/images/Cameras/19/19_1th.jpg', release_year: '2010', status: 'Discontinued', mount: 'A-mount', viewfinder: 'pentamirror', format: 'APS-C (1.5x)', effective_pixels: '16.2MP', max_resolution: '4912x3264' },
         'DSLR-a560' => { brand: 'SONY', full_name: 'Sony a560', dyxum_link: 'http://www.dyxum.com/gear/camera/a560/Sony_Alpha_560.asp', dyxum_img_link: '/images/Cameras/18/18_1th.jpg', release_year: '2010', status: 'Discontinued', mount: 'A-mount', viewfinder: 'pentamirror', format: 'APS-C (1.5x)', effective_pixels: '14.2MP', max_resolution: '4592x3056' },
         'DSLR-a390' => { brand: 'SONY', full_name: 'Sony a390', dyxum_link: 'http://www.dyxum.com/gear/camera/a390/Sony_Alpha_390.asp', dyxum_img_link: '/images/Cameras/17/17_1th.jpg', release_year: '2010', status: 'Discontinued', mount: 'A-mount', viewfinder: 'pentamirror', format: 'APS-C (1.5x)', effective_pixels: '14.2MP', max_resolution: '4592x3056' },
         'DSLR-a290' => { brand: 'SONY', full_name: 'Sony a290', dyxum_link: 'http://www.dyxum.com/gear/camera/a290/Sony_Alpha_290.asp', dyxum_img_link: '/images/Cameras/16/16_1th.jpg', release_year: '2010', status: 'Discontinued', mount: 'A-mount', viewfinder: 'pentamirror', format: 'APS-C (1.5x)', effective_pixels: '14.2MP', max_resolution: '4592x3056' },
         'NEX-5' => { brand: 'SONY', full_name: 'Sony NEX-5', dyxum_link: 'http://www.dyxum.com/gear/camera/NEX-5/Sony_Alpha_NEX-5.asp ', dyxum_img_link: '/images/Cameras/38/38_1th.jpg', release_year: '2010', status: 'Discontinued', mount: 'E-mount', viewfinder: 'none', format: 'APS-C (1.5x)', effective_pixels: '14MP', max_resolution: '4592x3056' },
         'NEX-3' => { brand: 'SONY', full_name: 'Sony NEX-3', dyxum_link: 'http://www.dyxum.com/gear/camera/NEX-3/Sony_Alpha_NEX-3.asp', dyxum_img_link: '/images/Cameras/33/33_1th.jpg', release_year: '2010', status: 'Discontinued', mount: 'E-mount', viewfinder: 'none', format: 'APS-C (1.5x)', effective_pixels: '14MP', max_resolution: '4592x3056' },
         'DSLR-a450' => { brand: 'SONY', full_name: 'Sony a450', dyxum_link: 'http://www.dyxum.com/gear/camera/a450/Sony_Alpha_450.asp', dyxum_img_link: '/images/Cameras/10/10_1th.jpg', release_year: '2010', status: 'Discontinued', mount: 'A-mount', viewfinder: 'pentamirror', format: 'APS-C (1.5x)', effective_pixels: '14.2MP', max_resolution: '4592x3056' },
         'DSLR-a850' => { brand: 'SONY', full_name: 'Sony a850', dyxum_link: 'http://www.dyxum.com/gear/camera/a850/Sony_Alpha_850.asp', dyxum_img_link: '/images/Cameras/14/14_1th.jpg', release_year: '2009', status: 'Discontinued', mount: 'A-mount', viewfinder: 'pentaprism', format: 'full frame (1x)', effective_pixels: '24.61MP', max_resolution: '6048x4032' },
         'DSLR-a550' => { brand: 'SONY', full_name: 'Sony a550', dyxum_link: 'http://www.dyxum.com/gear/camera/a550/Sony_Alpha_550.asp', dyxum_img_link: '/images/Cameras/12/12_1th.jpg', release_year: '2009', status: 'Discontinued', mount: 'A-mount', viewfinder: 'pentamirror', format: 'APS-C (1.5x)', effective_pixels: '14.2MP', max_resolution: '4592x3056' },
         'DSLR-a500' => { brand: 'SONY', full_name: 'Sony a500', dyxum_link: 'http://www.dyxum.com/gear/camera/a500/Sony_Alpha_500.asp', dyxum_img_link: '/images/Cameras/11/11_1th.jpg', release_year: '2009', status: 'Discontinued', mount: 'A-mount', viewfinder: 'pentamirror', format: 'APS-C (1.5x)', effective_pixels: '12.3MP', max_resolution: '4288x2856' },
         'DSLR-a380' => { brand: 'SONY', full_name: 'Sony a380', dyxum_link: 'http://www.dyxum.com/gear/camera/a380/Sony_Alpha_380.asp', dyxum_img_link: '/images/Cameras/9/9_1th.jpg', release_year: '2009', status: 'Discontinued', mount: 'A-mount', viewfinder: 'pentamirror', format: 'APS-C (1.5x)', effective_pixels: '14.2MP', max_resolution: '4592x3056' },
         'DSLR-a330' => { brand: 'SONY', full_name: 'Sony a330', dyxum_link: 'http://www.dyxum.com/gear/camera/a330/Sony_Alpha_330.asp', dyxum_img_link: '/images/Cameras/7/7_1th.jpg', release_year: '2009', status: 'Discontinued', mount: 'A-mount', viewfinder: 'pentamirror', format: 'APS-C (1.5x)', effective_pixels: '10.2MP', max_resolution: '3872x2592' },
         'DSLR-a230' => { brand: 'SONY', full_name: 'Sony a230', dyxum_link: 'http://www.dyxum.com/gear/camera/a230/Sony_Alpha_230.asp', dyxum_img_link: '/images/Cameras/5/5_1th.jpg', release_year: '2009', status: 'Discontinued', mount: 'A-mount', viewfinder: 'pentamirror', format: 'APS-C (1.5x)', effective_pixels: '10.2MP', max_resolution: '3872x2592' },
         'DSLR-a900' => { brand: 'SONY', full_name: 'Sony a900', dyxum_link: 'http://www.dyxum.com/gear/camera/a900/Sony_Alpha_900.asp', dyxum_img_link: '/images/Cameras/15/15_1th.jpg', release_year: '2008', status: 'Discontinued', mount: 'A-mount', viewfinder: 'pentaprism', format: 'full frame (1x)', effective_pixels: '24.61MP', max_resolution: '6048x4032' },
         'DSLR-a200' => { brand: 'SONY', full_name: 'Sony a200', dyxum_link: 'http://www.dyxum.com/gear/camera/a200/Sony_Alpha_200.asp', dyxum_img_link: '/images/Cameras/4/4_1th.jpg', release_year: '2008', status: 'Discontinued', mount: 'A-mount', viewfinder: 'pentamirror', format: 'APS-C (1.5x)', effective_pixels: '10.2MP', max_resolution: '3872x2592' },
         'DSLR-a700' => { brand: 'SONY', full_name: 'Sony a700', dyxum_link: 'http://www.dyxum.com/gear/camera/a700/Sony_Alpha_700.asp', dyxum_img_link: '/images/Cameras/13/13_1th.jpg', release_year: '2007', status: 'Discontinued', mount: 'A-mount', viewfinder: 'pentaprism', format: 'APS-C (1.5x)', effective_pixels: '12.24MP', max_resolution: '4288x2856' },
         'DSLR-a100' => { brand: 'SONY', full_name: 'Sony a100', dyxum_link: 'http://www.dyxum.com/gear/camera/a100/Sony_Alpha_100.asp', dyxum_img_link: '/images/Cameras/3/3_1th.jpg', release_year: '2006', status: 'Discontinued', mount: 'A-mount', viewfinder: 'pentamirror', format: 'APS-C (1.5x)', effective_pixels: '10MP', max_resolution: '3872x2592' },
         '5D' => { brand: 'Konica Minolta', full_name: 'Konica Minolta 5D', dyxum_link: 'http://www.dyxum.com/gear/camera/5d/konica_minolta_5D.asp', dyxum_img_link: '/images/Cameras/2/2_1th.jpg', release_year: '2005', status: 'Discontinued', mount: 'A-mount', viewfinder: 'pentamirror', format: 'APS-C (1.5x)', effective_pixels: '6.1MP', max_resolution: '3008x2000' },
         '7D' => { brand: 'Konica Minolta', full_name: 'Konica Minolta 7D', dyxum_link: 'http://www.dyxum.com/gear/camera/7d/konica_minolta_7D.asp', dyxum_img_link: '/images/Cameras/1/1_1th.jpg', release_year: '2004', status: 'Discontinued', mount: 'A-mount', viewfinder: 'pentaprism', format: 'APS-C (1.5x)', effective_pixels: '6.1MP', max_resolution: '3008x2000' } }

hash.each do |key, val|
  cam = CameraModel.where(name: key).first_or_initialize
  cam.update val
  cam.save
end
